services:
  shared-frontend:
    build:
      context: ./shared/frontend
    container_name: find-shared-frontend
    ports:
      - "16001:3000"
    volumes:
      - ./shared/css:/app/shared-css:ro
    depends_on:
      - shared-api
    networks:
      - find-network
    restart: unless-stopped

  shared-api:
    build:
      context: ./shared/backend
    container_name: find-shared-api
    ports:
      - "16002:5000"
    depends_on:
      - shared-db
    networks:
      - find-network
    restart: unless-stopped

  shared-db:
    build:
      context: ./shared/database
    container_name: find-shared-db
    ports:
      - "16003:6000"
    networks:
      - find-network
    restart: unless-stopped

  student-1-frontend:
    build:
      context: ./student-1/frontend
    container_name: find-student-1-frontend
    ports:
      - "16004:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - student-1-backend
    networks:
      - find-network
    restart: unless-stopped

  student-1-backend:
    build:
      context: ./student-1/backend
    container_name: find-student-1-backend
    ports:
      - "16005:5001"
    environment:
      NODE_ENV: development
      PORT: 5001
    depends_on:
      - student-1-db
    networks:
      - find-network
    restart: unless-stopped

  student-1-db:
    build:
      context: ./student-1/database
    container_name: find-student-1-db
    ports:
      - "16006:6001"
    environment:
      NODE_ENV: development
      PORT: 6001
    networks:
      - find-network
    restart: unless-stopped

networks:
  find-network:
    driver: bridge